name: github pages (daily deploy)

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  check:
    outputs:
      status: ${{ steps.update.conclusion }}
      steps:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: setup python to check modified date
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - id: update
        name: check modified date
        run: |
          python check_modified_date.py
        continue-on-error: true

  build-deploy:
    runs-on: ubuntu-18.04
    needs: check
    if: needs.check.outputs.status == 'success'
    steps:
      - uses: actions/checkout@v
        with:
          ref: main

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.10.x'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: install
        run: yarn install

      - name: build
        run: yarn run build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
